version: "3.9"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:8055:8080"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=${SERVICES-sqs,dynamodb,sns}
      - DEBUG=${DEBUG-1}
      - DATA_DIR=${HOST_TMP_FOLDER}/data
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mongodb:
    container_name: mongodb
    image: mongo:5.0-focal
    restart: always
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user 
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    networks:
      - bridge_mode

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - bridge_mode

networks:
  bridge_mode:
    driver: bridge
